baseURL = 'http://revindiecation.github.io/'
languageCode = 'es-MX'
title = 'RevINDIEcation'
theme = 'universal'
defaultContentLanguage = "es"
publishDir = 'public'

[params]
brandName = "RevINDIEcation ™"
